CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS PUBLIC.AUDITABLE_ENTITY
(
    id UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    date_created TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR,
    date_updated TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR,
    CONSTRAINT AUDITABLE_ENTITY_ID_PK PRIMARY KEY (ID)
)
TABLESPACE pg_default;

CREATE TABLE users (
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    user_name VARCHAR UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    phone_number VARCHAR UNIQUE,
    CONSTRAINT USERS_PK PRIMARY KEY (ID)
) INHERITS (AUDITABLE_ENTITY);

